version: '2.2'

services:
  laravel-echo-server:
    image: sunasteriskrnd/laravel-echo-server:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=6001
      - traefik.http.routers.laravel-echo.rule=Host(`${DOMAIN}`) && PathPrefix(`/socket.io`)
      - traefik.http.services.laravel-echo.loadbalancer.server.port=6001
    environment:
      - REDIS_HOST=redis
      - REDIS_KEY_PREFIX=${LARAVEL_ECHO_SERVER_REDIS_KEY_PREFIX}
      - NODE_ENV=development
      - AUTH_HOST=http://api:80
      - AUTH_ENDPOINT=/broadcasting/auth
